kafka:
  zeebe:
    timer: zeebe-timer
    error: zeebe-error
    incident: zeebe-incident
    job: zeebe-job
    message: zeebe-message
    message-subscription: zeebe-message-subscription
    message-start-event-subscription: zeebe-message-subscription-start-event
    process: zeebe-process
    process-event: zeebe-process-event
    process-instance: zeebe-process-instance
    process-instance-result: zeebe-process-instance-result
    variable: zeebe-variable

zeebe:
  client:
    broker.gatewayAddress: localhost:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: qual-account-app-hazelcast.account-app-hazelcast.svc.cluster.local:5701
        connectionTimeout: PT30S

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zeebe-simple-monitor
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

  kafka:
    listener.concurrency: 3
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: zeebe-simple-monitor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.zeebe.exporters.kafka.serde.RecordDeserializer
      enable-auto-commit: true


server:
  port: 8082
  servlet:
    context-path: /
  allowedOriginsUrls: ""

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: zeebe-simple-monitor

white-label:
  logo.path: img/logo.png
  custom:
    title: Zeebe Simple Monitor
    css.path: css/custom.css
    js.path: js/custom.js
